### ISSUE TITLE
Deploy a sample leaderboard on our VPS

### ISSUE THREAD

**Issue by captn3m0** [sdslabs/leaderboard#1]
Stuff to do:

1. Install dependencies and setup leaderboard.
1. Create a separate organization for the demo login on github
1. Remove organization check for login.
1. Setup a cronjob to update the scores every 5 minutes.

Use something like http://leaderboard-demo.sdslabs.co.in/

After that, we can deploy locally on http://score.sdslabs.co.in as well.

**Comment by abhshkdz** [comment]
I remember setting this up at some point. :raised_hands:
